include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AmēlijaPrefs

AmēlijaPrefs_FILES = AMLRootListController.m
AmēlijaPrefs_CFLAGS = -fobjc-arc
AmēlijaPrefs_FRAMEWORKS = UIKit
AmēlijaPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
AmēlijaPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk