BUNDLE_NAME = AmēlijaPrefs

AmēlijaPrefs_FILES = AMLRootVC.m
AmēlijaPrefs_CFLAGS = -fobjc-arc
AmēlijaPrefs_LIBRARIES = gcuniversal
AmēlijaPrefs_FRAMEWORKS = UIKit
AmēlijaPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
AmēlijaPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk